### ISSUE TITLE
Contract のコンパイルがうまくいきません

### ISSUE THREAD

**Issue by syoutaro** [cohki0305/notetoken_box#3]
サロンでもお世話になっているしょうです。申し訳ありません間違えてCloseしてしまったのでもう一度こちらで質問します。

contracts/NoteToken.solを作成して、
`$ truffle compile` を実行したのですが次のような結果になりました。

`Compiling ./contracts/Migrations.sol...`

`Compilation warnings encountered:`

`/Users/sugawarashoutarou/notetoken/contracts/Migrations.sol:11:3: Warning: Defining constructors as functions with the same name as the contract is deprecated. Use "constructor(...) { ... }" instead.
  function Migrations() public {
  ^ (Relevant source part starts here and spans across multiple lines).`

`Writing artifacts to ./build/contracts`

                                                                                                             
noteにある実行画面とは違います。

notetokenのディレクトリをlsで表示すると次のように表示されました。

`build			node_modules		scripts`
`config			package-lock.json	src`
`contracts		package.json		truffle-config.js`
`migrations		public			truffle.js`

contracts/NoteToken.sol _をremixのbrowserのところに作成してコードを書いた後に$_ truffle compileを実行しているのですがこの方法は間違っているのでしょうか？

**Comment by cohki0305** [comment]
@syoutaro 

> contracts/NoteToken.sol をremixのbrowserのところに作成してコードを書いた後に$ truffle compileを実行しているのですがこの方法は間違っているのでしょうか？

もしかしたらこちらが間違っているかもしれません 💦 
remix ではなくて、notetoken の contracts ディレクトリに `NoteToken.sol` を作成して頂く必要があります。

![project_ ___eth_notecoin](https://user-images.githubusercontent.com/12666715/39091390-f1577520-462d-11e8-8b43-e888463adea3.png)

truffle は contracts ディレクトリ以下の sol ファイルを compile するようになっているからです。

**Comment by cohki0305** [comment]
また `warning` なので compile 自体は上手く行ってそうです。ただ、デフォルトで存在する `Migrations.sol` のみがデプロイ対象になっているようです。

> Compiling ./contracts/Migrations.sol...

僕の環境では再現しないので、確信はないのですが、以下のように変更すると warning が消えるかもしれません

```diff
- pragma solidity ^0.4.17;
+ pragma solidity ^0.4.19;
```

> emit is a keyword introduced in solidity 0.4.21. The contracts have only been tested with solc 0.4.19
ref. https://github.com/ConsenSys/Linnia-Smart-Contracts/issues/20#issuecomment-378134974

また以下のコメント通りに実行することで動作の確認を行うことも可能です。

https://github.com/cohki0305/notetoken_box/issues/1#issuecomment-382548945

**Comment by syoutaro** [comment]
指摘してくださった通りに実行したらcompileすることができました！

ありがとうございます！

**Comment by cohki0305** [comment]
@syoutaro 

上手く行って良かったです！note の方も修正しておきました！

ありがとうございました！
