### ISSUE TITLE
SimpleStorage.solのsetコードについて

### ISSUE THREAD

**Issue by kokodesu** [cohki0305/notetoken_box#4]
お世話になっております。

DApps入門のnoteを購入させていただきました。
SimpleStorage.solのsetコードを記入してデプロイしたのですが、
noteの画像のようなsetフォームがでません。
なにかほかに方法はございますでしょうか。
よろしくお願いいたします。

setコード
https://gyazo.com/d47ffe7acbac4944cee30a7ca7d25d02

デプロイ後
https://gyazo.com/f6111a6156cc05d9190676b70f63c579

**Comment by cohki0305** [comment]
@kokodesu 
購入ありがとうございます！

画像貼っていただきありがとうございます！
コードは正しい気がしたので、表示されていないのはおかしいですね... 🤔 

削除してから再デプロイしてみても同じ結果になりますか？？

**Comment by kokodesu** [comment]
＠cohki0305
さっそくのご返信いただきありがとうございます！
削除して再デプロイしてみたらできました！

再デプロイ後
https://gyazo.com/570bf9206702863c77165a5abce498d8

お騒がせいたしました。
引き続き進めてまいりたいと思います。
ありがとうございます。

**Comment by cohki0305** [comment]
@kokodesu 
うまく行ってよかったです 🎉 

解決したので issue はクローズしますね！
