### ISSUE TITLE
[独自トークの送金アプリを開発する] でのエラー

### ISSUE THREAD

**Issue by roy1210** [cohki0305/notetoken_box#6]
とださん
お世話になります。呉(クレ)と申します。　
いつもブログ、ツイッターを楽しく拝見させていただいております！

表題の件の段落でエラーが出てしまい、自力で解決方法を探すも見つからず、ご教授いただきたく思います。
src/index.js がからの状態だとhttp://localhost:3000 ではNote Tokenと問題なく表示されますが、
以下のコードをindex.jsに入れると「Module not found: Can't resolve 'web3'」のエラーが出てしまいます。

心あたりは一つあります。ターミナルにて「npm install zeppelin-solidity@1.8.0 --save」を入力した際、
ログではERRがたくさん見られました。このコマンドを実行する前後のどこかで間違えがあったことが起因している事でしょうか。
下記URLにてRepoをアップロードしましたので、お手数ですがご指導おねがいします。
ログでのエラーは「181111 Error Log」よりご参照願います。

index.js
```
import Web3 from 'web3'

const provider = new Web3.providers.HttpProvider('http://127.0.0.1:7545')
const web3 = new Web3(provider)

web3.eth.getAccounts().then((accounts) => {
  console.log(accounts[0])
})
```

Repo:
https://bitbucket.org/roy1210/truffletutorial_makeoriginalcoin/src/master/

Screenshot:
https://i.gyazo.com/74115668266b045631f7a712703ef734.png

補足：
下記URLを参考にnpm install truffle-contractとnpm install -g truffle-contractを試しましたが、だめでした。
https://www.edureka.co/community/11845/how-to-solve-module-not-found-error-in-web3

**Comment by cohki0305** [comment]
反応遅れました 🙇 

> Module not found: Can't resolve 'web3'

ということなので、おそらく web3 がインストールされていないのだと思います。

```
$ npm install web3
```

を実行するとどうなりますか？

**Comment by cohki0305** [comment]
> このコマンドを実行する前後のどこかで間違えがあったことが起因している事でしょうか。

この可能性もありますが、環境依存による問題である可能性も十分ありそうです。

**Comment by cohki0305** [comment]
bitbucket のリンクを確認しましたが、閲覧できませんでした 😓 
権限の問題だと思います。

**Comment by roy1210** [comment]
とださん
ご返信ありがとうございます。　Repo、名前を修正したせいで開けないようです。
https://bitbucket.org/roy1210/truffle_tutorial_make_original_coin/src/master/

なお、npm install web3で試してみたら無事「Note Token」が表示され、ConsoleではGANACHEからログイン中のAddressが表示されましたので、上手く行っていると思います!

本コースで別途わからないことがございましたら質問いたしますので、
その際はご対応おねがいします。

**Comment by cohki0305** [comment]
よかったです！

何かあれば気軽に聞いてください！

**Comment by cohki0305** [comment]
解決したのでこの issue は Close しますね！
